version: '3.0'
services:
  app:
    depends_on:
      - db
    build:
      context: ./docker # thư mục chứa Dockerfile muốn build app
      dockerfile: ./app/Dockerfile
    
    volumes:
      - ./application/blog:/app_blog
      - bundle_volumes:/usr/local/bundle
    command: sh /scripts/command.sh
    ports:
      - 5000:5000
  
  db:
    build:
      context: ./database
      dockerfile: ./Dockerfile.postgresql
    environment:
      - POSTGRES_USER=vareal
      - POSTGRES_PASSWORD=vareal
    volumes:
      - db_volumes:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  bundle_volumes:
  db_volumes:


